name = "sample_project"
version = "0.1.0"
description = "a web project"

target = "javascript"

[javascript]
typescript_declarations = true

[dependencies]
gleam_stdlib = "~> 0.30"
lustre = "~> 3.0.0-rc.8"

